repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
        name: Lint Markdown files
        files: ^docs/.*\.md$
        args: ["--fix"]
        
  - repo: local
    hooks:
      - id: mkdocs-build-check
        name: MkDocs Build Check
        entry: mkdocs build --strict --quiet
        language: system
        files: ^(docs/.*\.md|mkdocs\.yml)$
        pass_filenames: false
      - id: markdownlint-strict
        name: Strict Markdown Linting (Final Check)
        entry: bash -c 'markdownlint-cli2 docs/**/*.md || (echo "❌ Markdown linting failed after fixes. Please review manually." && exit 1)'
        language: system
        files: ^docs/.*\.md$
        pass_filenames: false
        stages: [pre-commit]
        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        files: ^mkdocs\.yml$
      - id: check-merge-conflict
      - id: trailing-whitespace
        files: ^docs/.*\.md$
      - id: end-of-file-fixer
        files: ^docs/.*\.md$
      - id: check-added-large-files
